# Generated by Django 5.2.7 on 2026-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('채소', '채소'), ('양념', '양념'), ('해산물', '해산물'), ('육류', '육류'), ('가공식품', '가공식품'), ('조미료', '조미료'), ('과일', '과일')], default='채소', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
