# Generated by Django 6.0.1 on 2026-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
