# Generated by Django 6.0.1 on 2026-01-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_django", "0004_alter_ingredient_quantity_alter_ingredient_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cooking_step", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="my_recipe")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("쉬움", "쉬움"),
                            ("보통", "보통"),
                            ("어려움", "어려움"),
                        ],
                        default="보통",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="my_django.masteringredient",
                        verbose_name="필요한 재료",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
