# Generated by Django 5.2.7 on 2026-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True)),
                ('cooking_step', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='my_recipe')),
                ('difficulty', models.CharField(choices=[('쉬움', '쉬움'), ('보통', '보통'), ('어려움', '어려움')], max_length=20)),
            ],
        ),
    ]
